##	radio-mb86a30v-objs	:= radio-mb86a30v.o
##obj-$(CONFIG_RADIO_MB86A30V) += radio-mb86a30v.o
obj-m += radio-mb86a30v.o
##	CONFIG_RADIO_MB86A30V=y
#
##	obj-$(CONFIG_RADIO_MB86A30V) += radio-mb86a30v.o
#
#ifeq ($(CONFIG_DEBUG_DRIVER),y)
EXTRA_CFLAGS += -DDEBUG
#endif
#
#ifeq ($(ARCH),i386)
#EXTRA_CFLAGS += -DDEBUG_I386
#endif
