# Device Support
obj-$(CONFIG_FUJITSU_TOUCHPANEL) += touchpanel/
obj-$(CONFIG_FUJITSU_LIGHT) += light/
obj-$(CONFIG_FUJITSU_LIGHT) +=  sitronix/
obj-$(CONFIG_FUJITSU_WALKMOTION) += walkmotion/
obj-$(CONFIG_FUJITSU_COMPASS) += compass/
obj-$(CONFIG_FUJITSU_IRDA) += irda/
obj-y += stschk/
obj-y += testmode/
#obj-$(CONFIG_FUJITSU_FELICA) += felica/
obj-$(CONFIG_FUJITSU_FCFD) += fcfd/
obj-$(CONFIG_FUJITSU_FCSMD) += fcsmd/
# FUJITSU:2012/03/27 add for TMS start
obj-y += pipe/
obj-y += memread/
# FUJITSU:2012/03/27 add for TMS end
